server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: acme-app
            client-secret: acmesecret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost:9001/realms/acme-realm/protocol/openid-connect/auth
            token-uri: http://localhost:9001/realms/acme-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:9001/realms/acme-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:9001/realms/acme-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username