services:
  acme-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: acme-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9001:8080"
    volumes:
      - ./acme-realm.json:/opt/keycloak/data/import/acme-realm.json
      - ./entrypoint.sh:/opt/keycloak/entrypoint.sh
    command: >
      /bin/bash -c "chmod +x /opt/keycloak/entrypoint.sh && /opt/keycloak/entrypoint.sh"

  globex-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: globex-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9002:8080"
    volumes:
      - ./globex-realm.json:/opt/keycloak/data/import/globex-realm.json
      - ./entrypoint.sh:/opt/keycloak/entrypoint.sh
    command: >
      /bin/bash -c "chmod +x /opt/keycloak/entrypoint.sh && /opt/keycloak/entrypoint.sh"
