services:
  acme-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: acme-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9001:8080"  # Maps port 9001 on host to port 8080 in container
    volumes:
      - ./acme-realm.json:/opt/keycloak/data/import/acme-realm.json
      - acme-data:/opt/keycloak/data
    command:
      - start-dev
      - --import-realm

  globex-keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: globex-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9002:8080"  # Maps port 9002 on host to port 8080 in container
    volumes:
      - ./globex-realm.json:/opt/keycloak/data/import/globex-realm.json
      - globex-data:/opt/keycloak/data
    command:
      - start-dev
      - --import-realm

volumes:
  acme-data:
  globex-data:
